const List<Map<String, dynamic>> questions = [{
  "id":"Not_Cid",
  "name":"Como você fica sabendo das nóticias sobre a cidade?",
  "isMulti": true,
  "options":["Carro de Som", "Conversas Informais", "Rádio", "Redes Sociais", "Site da Prefeitura", "Televisão", "Whatsapp", "Outros"],
},
{
  "id":"Loc_Trav",
  "name":"Cite até três locais que você frequenta além do trabalho",
  "isMulti": true,
  "options":["Academia", "Bares/Restaurantes", "Casa Família/Amigos", "Clube/Pesqueiro", "Escola", "Feira/Comércio", "Igreja/Culto", "Lago/Rio", "Praças/Parques", "Quadra de Esporte", "Shows", "Sindicato/Associações/Partidos", "Outros"],
},
{
  "id":"Pri_Bair",
  "name":"Cite até três prioridades para seu bairro ou região:",
  "isMulti": true,
  "options":["Ação Social", "Arborização", "Coleta de Lixo", "combustível", "Cresche", "Cultura/Eventos", "emprego", "Escola/Cursos", "Esporte/Lazer/Recreação", "Faculdade", "Farmácia", "Habitação", "Hospital", "Iluminação", "Ônibus", "Pavimentação", "Posto de Saúde", "Praça", "Reciclagem", "Segurança", "Saneamento", "Trânsito", "Turismo", "Outros"],
},
{
  "id":"Cuid_Saud",
  "name":"Como você cuida da sua saúde?",
  "isMulti": true,
  "options":["Academia", "Alimentação balanceada", "Bebe água", "Caminha/Corre", "Dança", "Dorme", "Esporte", "Exames/Remédio", "Outro", "Não Cuida"],
},
{
  "id":"Loc_Laz",
  "name":"Cite até três locais que você usa/usaria para lazer:",
  "isMulti": true,
  "options":["Academia pública", "Biblioteca", "Ciclofaixas", "Cómercio", "Lago/Rio", "Parque/Praça", "Pista de Caminhada", "Quadra de Esportes", "Outro"],
},
{
  "id":"Res_Dom",
  "name":"O seu resíduo doméstico/lixo é separado? Onde você o descarta?",
  "isMulti": true,
  "options":["Não separa", "Separa seco e orgânico", "Calçada/Lixeira", "Compostagem", "Enterra", "Queima", "Rio/Córrego", "terreno", "Vende/Doa material"],
},
{
  "id":"Dei_Res",
  "name":"Onde prefere deixar o resíduo doméstico para reciclagem?",
  "isMulti": true,
  "options":["Não pretende separar o resíduo.", "Na calçada/lixeira para coleta da Coop Recicla ou outra empresa.", "No PEV (Ponto de Entrega Voluntária) instalado próximo da residência.", "Entrega direto na Coop Recicla (Cooperativa de Reciclagem do Sudoeste Goiano).", "Armazenar em casa para venda, doação ou destino posterior."],
},
{
  "id":"Fre_Res",
  "name":"Com qual frequência acontece a coleta de resíduo na sua rua?",
  "isMulti": false,
  "options":["1 ou 2x na semana", "3x na semana ou mais", "1x no mês", "Não tem coleta", "Não sabe"],
},
{
  "id":"Fre_Var",
  "name":"Com qual frequência é feita a varrição da rua pelos garis?",
  "isMulti": false,
  "options":["1 ou 2x na semana", "3x na semana ou mais", "1x no mês", "Não tem coleta", "Não sabe"],
},
{
  "id":"Ben_Arb",
  "name":"Quais os benefícios da arborização das ruas?",
  "isMulti": true,
  "options":["Ar puro/fresco", "Embeleza a cidade", "Preservação", "Qualidade de vida", "Sombra", "Valoriza o imóvel", "Sem benefícios", "Outro"],
},
{
  "id":"Ori_Agu",
  "name":"Qual a origem da água para consumo humano na sua casa?",
  "isMulti": true,
  "options":["Água mineral", "Chuva/Armazenagem", "Cisterna", "Filtro", "Poço Artesiano", "Rio/Bica/Nascente", "Torneira/Rede pública", "Outra"],
},
{
  "id":"Falt_Agu",
  "name":"Ocorre falta de água? Com qual Frequência?",
  "isMulti": false,
  "options":["1 ou 2x na semana", "3x na semana ou mais", "1x no mês", "Falta na estação seca", "Nunca falta", "Não sabe"],
},
{
  "id":"Mei_Tran",
  "name":"Qual meio de transporte que você mais utiliza?",
  "isMulti": true,
  "options":["A pé", "Animal", "Bicicleta", "Camionete", "Carro", "Carona/Uber/Táxi", "Motocicleta", "Ônibus municipal", "Transporte empresa"],
},
{
  "id":"Sat_Vid",
  "name":"De 1 a 5, qual o grau de satisfação com a sua qualidade de vida?",
  "isMulti": false,
  "options":["1 - muito insatisfeito", "2 - insatisfeito", "3 - indiferente/não sabe", "4 - satisfeito", "5 - muito satisfeito"],
},
{
  "id":"Sat_Gov",
  "name":"De 1 a 5, qual o grau de satisfação com o governo municipal?",
  "isMulti": false,
  "options":["1 - muito insatisfeito", "2 - insatisfeito", "3 - indiferente/não sabe", "4 - satisfeito", "5 - muito satisfeito"],
},
];